### ISSUE TITLE
config.ts is being ignored

### ISSUE THREAD

**Issue by Alex-joomla** [lewisdoesstuff/bento-next#7]
**Describe the bug**
I installed your Bento fork via docker compose. That is:
```
  bento:
    image: lewisdoesstuff/bento-next
    volumes:
      # Append Bento config/.env location to below line.
      - ./bento/config.ts:/usr/share/nginx/html/config.ts
      - ./bento/.env:/usr/share/nginx/html/.env
    ports:
      # Replace host port 80 (left side) with desired port.
      - 8900:8080
```

I have the config.ts in place but bento just uses defaults and ignores what I'm changing in the config file.

** Device Details  (please complete the following information):**
 - OS: MacOSX Sonoma
 - Browser Chrome

**Comment by lewisdoesstuff** [comment]
I _might_ have forgotten to update the compose file here, can you change the `./bento/config.ts:/usr/share/nginx/html/config.ts` line to `/bento/config.ts:/src/config.ts`?

At least in my personal instance, that's what I'm using, but I can't remember if that was for some other reason

**Comment by Alex-joomla** [comment]
Unfortunately no difference. Got now:
```
bento:
    image: lewisdoesstuff/bento-next
    volumes:
      # Append Bento config/.env location to below line.
      - ./bento/config.ts:/src/config.ts
      - ./bento/.env:/usr/share/nginx/html/.env
    ports:
      # Replace host port 80 (left side) with desired port.
      - 8900:8080
```
And 

<img width="567" alt="Bildschirmfoto 2024-08-06 um 22 52 50" src="https://github.com/user-attachments/assets/5afed348-9de9-4bd5-909d-c2df81abeb61">


but I'm still John
<img width="689" alt="Bildschirmfoto 2024-08-06 um 22 53 14" src="https://github.com/user-attachments/assets/08b04799-31cd-4843-b897-9ce49b054f1f">
